// use dev or prod variables
import { INSIDE_OCR_SERVER_URL, INSIDE_SUBSCRIPTION_KEY, INSIDE_ADMOB_ID } from "./env.production"
//import { INSIDE_OCR_SERVER_URL, INSIDE_SUBSCRIPTION_KEY, INSIDE_ADMOB_ID } from "./env.development"

export const OCR_SERVER_URL = INSIDE_OCR_SERVER_URL
export const SUBSCRIPTION_KEY = INSIDE_SUBSCRIPTION_KEY
export const ADMOB_ID = INSIDE_ADMOB_ID